name: Prune Posts and Archive

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'posts/**'
  schedule:
    - cron: '12 4 * * 2'  # Runs at 04:12, only on Tuesday
  workflow_dispatch:


jobs:
  archive_old_posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare archive and delete files
        id: prune
        run: |
          cd posts
          total_files=$(ls -1 | wc -l)
          echo "Total files in posts: $total_files"

          if [ "$total_files" -gt 40 ]; then
            to_delete=$((total_files - 20))
            echo "Deleting $to_delete oldest files"

            files_to_delete=$(ls -1tr | head -n $to_delete)
            echo "$files_to_delete"

            date_tag=$(date +'%Y-%m-%d')
            archive_name="../Archive-${date_tag}.tar.gz"
            echo "Creating archive $archive_name"

            tar -czf "$archive_name" $files_to_delete
            echo "Archive created."

            echo "$files_to_delete" | xargs rm -f
            echo "Files deleted."

            cd ..
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add posts
            git commit -m "chore: deleted old posts and archived on $date_tag"
            git push origin HEAD
            echo "Changes committed and pushed."

            echo "archive_name=$archive_name" >> $GITHUB_OUTPUT
            echo "deleted=true" >> $GITHUB_OUTPUT
            echo "tag_name=archive-${date_tag}" >> $GITHUB_OUTPUT
          else
            echo "deleted=false" >> $GITHUB_OUTPUT
          fi

      - name: Create or update release with archive
        if: steps.prune.outputs.deleted == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.prune.outputs.tag_name }}
          name: "Archive: ${{ steps.prune.outputs.tag_name }}"
          body: "Auto archive of deleted posts on ${{ steps.prune.outputs.tag_name }}"
          draft: true
          prerelease: true
          files: ${{ steps.prune.outputs.archive_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
