name: Limit Posts Folder to 20 Files

on:
  push:
    paths:
      - 'posts/**'
  workflow_dispatch:

jobs:
  manage-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Limit /posts to 20 files
        run: |
          cd posts
          total_files=$(ls -1 | wc -l)
          echo "Total files in posts: $total_files"
          if [ "$total_files" -gt 20 ]; then
            to_delete=$((total_files - 20))
            echo "Deleting $to_delete oldest files"
            ls -1tr | head -n $to_delete | xargs rm -f
          else
            echo "No files need to be deleted."
          fi

      - name: Commit changes if any files deleted
        run: |
          if [[ -n $(git status -s) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add posts/
            git commit -m "chore: prune posts folder to max 20 files"
            git push
          else
            echo "No changes to commit."
          fi
