name: Archive and Clean Up Old Posts

on:
  schedule:
    - cron: '12 4 * * 2'  # Runs at 04:12, only on Tuesday
  workflow_dispatch:

jobs:
  archive_cleanup:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: List posts and check if we need to archive
        run: |
          posts=$(ls -1 ./posts/*.md | sort -r)
          total_posts=$(echo "$posts" | wc -l)

          if [ "$total_posts" -gt 120 ]; then
            echo "Total posts: $total_posts. Proceeding with archive and cleanup."

            oldest_posts=$(echo "$posts" | tail -n 20)

            start_date=$(head -n 1 <<< "$oldest_posts" | xargs -I {} stat --format='%y' {} | cut -d' ' -f1)
            end_date=$(tail -n 1 <<< "$oldest_posts" | xargs -I {} stat --format='%y' {} | cut -d' ' -f1)
            release_name="archive-${start_date}_to_${end_date}"

            echo "Creating release with the following posts: $oldest_posts"
            gh release create "$release_name" $oldest_posts --title "$release_name" --notes "Archived posts from $start_date to $end_date."

            echo "Removing posts: $oldest_posts"
            rm $oldest_posts

            git add ./posts/
            git commit -m "optimization: Removed oldest posts and archived them"
            git push origin main
          else
            echo "No need to archive. Total posts are $total_posts."
